MultiShop.Presentation/Controllers/HomeController.cs
namespace MultiShop.Presentation.Controllers
{
    public class HomeController(ICategoryService categoryService, ISliderService sliderService, IProductService productService):  Controller
    {
        readonly ICategoryService _categoryService = categoryService;
        readonly ISliderService _sliderService=sliderService;
        readonly IProductService _productService=productService;
        public IActionResult Index()
        {
            //var predicate =new List<Expression<Func<Category, bool>>>();

            //predicate.Add(c=> c.CategoryId == 1);

            //var categories = _categoryService.GetCategories().AsQueryable().Where(predicate[0]);
            var predicate = new List<Func<CategoryDto, bool>>();
            predicate.Add(c => c.CategoryId == 1);

            //select * from Where //Sorgulanabilir 
            var categores = _categoryService.GetCategories().AsQueryable().Where(predicate[0]);

            //var slider = _sliderService.GetSliders();
            var product = _productService.GetProducts();
            return View();

        }
        [Experimental("thisLineWillbeCheck")]
        public void DeleteAllUsers()
        {
            //Raw String 
            var favoriteNumber = 5;

            var query = $"""
                 select $* 
                 from Product
                 where price>{favoriteNumber}
                 order by price asc
                """;

        }

    }
}

MultiShop.Presentation/Views/Home/Components/Category/CategoryViewComponent.cs
namespace MultiShop.Presentation
{
    public class CategoryViewComponent(ICategoryService categoryService):ViewComponent
    {
        readonly ICategoryService  _categoryService=categoryService;
        public IViewComponentResult Invoke()
        {
            List<CategoryDto> categories = _categoryService.GetCategoriesWithProductCount();
            return View(categories);
        }
    }
}

MultiShop.Presentation/Views/Home/Components/Product/ProductViewComponent.cs
namespace MultiShop.Presentation.Views.Home.Components.Product
{
    public class ProductViewComponent(IProductRatingService productRatingService) : ViewComponent
    {
        readonly IProductRatingService _productRatingService = productRatingService;
        public IViewComponentResult Invoke(ProductHeaderType productHeaderType)
        {
            List<ProductDto> products = _productRatingService.GetProductWithRatings(productHeaderType);
            return View(products);
        }
    }
}

MultiShop.Presentation/Views/Shared/Components/Footer/FooterViewComponent.cs
namespace MultiShop.Presentation
{
    public class FooterViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        { 
           return View(); 
        }
    }
}

MultiShop.Presentation/Views/Shared/Components/NavBar/NavBarViewComponent.cs
namespace MultiShop.Presentation
{
    public class NavBarViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public NavBarViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            List<CategoryDto> categories = _categoryService.GetCategories();
            return View(categories);
        }
    }
}

MultiShop.Presentation/Views/Shared/Components/Product/ProductViewComponent.cs
namespace MultiShop.Presentation
{
    public class ProductViewComponent(IProductRatingService productRatingService) :ViewComponent
    {
        readonly IProductRatingService _productRatingService = productRatingService;
        public IViewComponentResult Invoke(ProductHeaderType productHeaderType)
        {
            List<ProductDto> products = _productRatingService.GetProductWithRatings(productHeaderType);
            return View(products);
        }
    }
}

MultiShop.Presentation/Views/Shared/Components/SliderBottom/SliderBottomViewComponent.cs
namespace MultiShop.Presentation.Views
{
    public class SliderBottomViewComponent(ISliderService sliderService) : ViewComponent
    {
        private readonly ISliderService _sliderService = sliderService;

        public IViewComponentResult Invoke()
        {
            List<SliderDto> sliders = _sliderService.GetSliders(SliderPosition.Bottom);

            return View(sliders);
        }
    }
}

MultiShop.Presentation/Views/Shared/Components/SliderLeft/SliderLeftViewComponent.cs
namespace MultiShop.Presentation.Views
{
    public class SliderLeftViewComponent(ISliderService sliderService) : ViewComponent
    {
        private readonly ISliderService _sliderService = sliderService;

        public IViewComponentResult Invoke()
        {
            List<SliderDto> sliders = _sliderService.GetSliders(SliderPosition.Left);

            return View(sliders);
        }
    }
}

MultiShop.Presentation/Views/Shared/Components/SliderRight/SliderRightViewComponent.cs
namespace MultiShop.Presentation.Views
{
    public class SliderRightViewComponent(ISliderService sliderService) : ViewComponent
    {
        private readonly ISliderService _sliderService = sliderService;

        public IViewComponentResult Invoke()
        {
            List<SliderDto> sliders = _sliderService.GetSliders(SliderPosition.Right);
            return View(sliders);
        }
    }
}

MultiShop.Presentation/Views/Shared/Components/TopBar/TopBarViewComponent.cs
namespace MultiShop.Presentation
{
    public class TopBarViewComponent : ViewComponent
    {    //TopBar
            public IViewComponentResult Invoke()
            {
                return View();
            }
    }
}

MultiShop.Presentation/Views/Home/Components/Category/Default.cshtml
@using MultiShop.Business;
@model List<CategoryDto>

<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Categories</span></h2>
    <div class="row px-xl-5 pb-3">
      @foreach (CategoryDto category in Model)
      {
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <a class="text-decoration-none" href="">
                    <div class="cat-item d-flex align-items-center mb-4">
                        <div class="overflow-hidden" style="width: 100px; height: 100px;">
                            <img class="img-fluid" src="@category.Image" alt="">
                        </div>
                        <div class="flex-fill pl-3">
                            <h6>@category.CategoryName</h6>
                            <small class="text-body">@category.ProductCount</small>
                        </div>
                    </div>
                </a>
            </div>
      }
    </div>
</div>

MultiShop.Presentation/Views/Home/Components/Product/Default.cshtml
@using MultiShop.Business
@model List<ProductDto>
<@foreach (ProductDto product in Model)
{
    <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
        <div class="product-item bg-light mb-4">
            <div class="product-img position-relative overflow-hidden">
                <img class="img-fluid w-100-h-300" src="@product.Image" alt="">
                <div class="product-action">
                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
                    <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                </div>
            </div>
            <div class="text-center py-4">
                <a class="h6 text-decoration-none text-truncate" href="">@product.ProductName</a>
                <div class="d-flex align-items-center justify-content-center mt-2">
                    <h5>@product.Price</h5><h6 class="text-muted ml-2"><del>@product.DistcountedPrice</del></h6>
                </div>
                <div class="d-flex align-items-center justify-content-center mb-1">
                    @for (int i = 0; i < product.ProductRating; i++)
                    {
                                <small class="fa fa-star text-primary mr-1"></small>
                    }
                           <small>(@product.ProductRating)</small>
                </div>
            </div>
        </div>
    </div>
}

MultiShop.Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<!-- Carousel Start -->
<div class="container-fluid mb-3">
    <div class="row px-xl-5">
        <div class="col-lg-8">
           @await Component.InvokeAsync("SliderLeft")
        </div>
        <div class="col-lg-4">
            @await Component.InvokeAsync("SliderRight")
        </div>
    </div>
</div>
<!-- Carousel End -->
<!-- Featured Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
            </div>
        </div>
    </div>
</div>
<!-- Featured End -->
<!-- Categories Start -->
@await Component.InvokeAsync("Category")
<!-- Categories End -->
<!-- Products Start -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Featured Products</span></h2>
    <div class="row px-xl-5">
        @await Component.InvokeAsync("Product", ProductHeaderType.FeaturedProducts)
    </div>
</div>

<!-- Products End -->
<!-- Offer Start -->
<div class="container-fluid pt-5 pb-3">
    <div class="row px-xl-5">
        <div class="col-md-6">
            <div class="product-offer mb-30" style="height: 300px;">
                <img class="img-fluid" src="~/ui/img/offer-1.jpg" alt="">
                <div class="offer-text">
                    <h6 class="text-white text-uppercase">Save 20%</h6>
                    <h3 class="text-white mb-3">Special Offer</h3>
                    <a href="" class="btn btn-primary">Shop Now</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="product-offer mb-30" style="height: 300px;">
                <img class="img-fluid" src="~/ui/img/offer-2.jpg" alt="">
                <div class="offer-text">
                    <h6 class="text-white text-uppercase">Save 20%</h6>
                    <h3 class="text-white mb-3">Special Offer</h3>
                    <a href="" class="btn btn-primary">Shop Now</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Offer End -->
<!-- Products Start -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Recent Products</span></h2>
    <div class="row px-xl-5">
        @await Component.InvokeAsync("Product", ProductHeaderType.RecentProducts)
    </div>
</div>
<!-- Products End -->
<!-- Vendor Start -->
<div class="container-fluid py-5">
    <div class="row px-xl-5">
        <div class="col">
            <div class="owl-carousel vendor-carousel">
                <div class="bg-light p-4">
                    <img src="~/ui/img/vendor-1.jpg" alt="">
                </div>
                <div class="bg-light p-4">
                    <img src="~/ui/img/vendor-2.jpg" alt="">
                </div>
                <div class="bg-light p-4">
                    <img src="~/ui/img/vendor-3.jpg" alt="">
                </div>
                <div class="bg-light p-4">
                    <img src="~/ui/img/vendor-4.jpg" alt="">
                </div>
                <div class="bg-light p-4">
                    <img src="~/ui/img/vendor-5.jpg" alt="">
                </div>
                <div class="bg-light p-4">
                    <img src="~/ui/img/vendor-6.jpg" alt="">
                </div>
                <div class="bg-light p-4">
                    <img src="~/ui/img/vendor-7.jpg" alt="">
                </div>
                <div class="bg-light p-4">
                    <img src="~/ui/img/vendor-8.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Vendor End -->

MultiShop.Presentation/Views/Shared/Components/Footer/Default.cshtml
@{

}

<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
            <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum tempor no vero est magna amet no</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                    <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Your Email Address">
                            <div class="input-group-append">
                                <button class="btn btn-primary">Sign Up</button>
                            </div>
                        </div>
                    </form>
                    <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                by
                <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="~/ui/img/payments.png" alt="">
        </div>
    </div>
</div>

MultiShop.Presentation/Views/Shared/Components/NavBar/Default.cshtml
@using MultiShop.Business

@model List<CategoryDto>

<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
@*                     <div class="nav-item dropdown dropright">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Dresses <i class="fa fa-angle-right float-right mt-1"></i></a>
                        <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                            <a href="" class="dropdown-item">Men's Dresses</a>
                            <a href="" class="dropdown-item">Women's Dresses</a>
                            <a href="" class="dropdown-item">Baby's Dresses</a>
                        </div>
                    </div>
                    <a href="" class="nav-item nav-link">Shirts</a>
                    <a href="" class="nav-item nav-link">Jeans</a>
                    <a href="" class="nav-item nav-link">Swimwear</a>
                    <a href="" class="nav-item nav-link">Sleepwear</a>
                    <a href="" class="nav-item nav-link">Sportswear</a>
                    <a href="" class="nav-item nav-link">Jumpsuits</a>
                    <a href="" class="nav-item nav-link">Blazers</a>
                    <a href="" class="nav-item nav-link">Jackets</a>
                    *@

                    @foreach (var item in Model)
                    {
                        <a href="" class="nav-item nav-link">@item.CategoryName</a>

                    }
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="index.html" class="nav-item nav-link active">Home</a>
                        <a href="shop.html" class="nav-item nav-link">Shop</a>
                        <a href="detail.html" class="nav-item nav-link">Shop Detail</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages <i class="fa fa-angle-down mt-1"></i></a>
                            <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                                <a href="cart.html" class="dropdown-item">Shopping Cart</a>
                                <a href="checkout.html" class="dropdown-item">Checkout</a>
                            </div>
                        </div>
                        <a href="contact.html" class="nav-item nav-link">Contact</a>
                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        <a href="" class="btn px-0">
                            <i class="fas fa-heart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                        </a>
                        <a href="" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

MultiShop.Presentation/Views/Shared/Components/SliderBottom/Default.cshtml
@using MultiShop.Business

@model List<SliderDto>

@foreach (SliderDto sliderDto in Model)
{
    <div class="col-md-6">
        <div class="product-offer mb-30" style="height: 300px;">
            <img class="img-fluid" src="@sliderDto.Image" alt="">
            <div class="offer-text">
                <h6 class="text-white text-uppercase">Save 20%</h6>
                <h3 class="text-white mb-3">@sliderDto.Header</h3>
                <a href="" class="btn btn-primary">Shop Now</a>
            </div>
        </div>
    </div>
}

MultiShop.Presentation/Views/Shared/Components/SliderLeft/Default.cshtml
@model List<SliderDto>


<div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
    <ol class="carousel-indicators">

        @foreach (SliderDto sliderDto in Model)
        {
            @if (sliderDto.Order.HasValue && sliderDto.Order == 1)
            {
                <li data-target="#header-carousel" data-slide-to="@(sliderDto.Order - 1)" class="active"></li>
            }
            else
            {
                <li data-target="#header-carousel" data-slide-to="@(sliderDto.Order - 1)"></li>
            }

        }

    </ol>
    <div class="carousel-inner">


        @foreach (SliderDto sliderDto in Model)
        {
            @if (sliderDto.Order.HasValue && sliderDto.Order == 1)
            {
                <div class="carousel-item position-relative active" style="height: 430px;">
                    <img class="position-absolute w-100 h-100" src="@sliderDto.Image" style="object-fit: cover;">
                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                        <div class="p-3" style="max-width: 700px;">
                            <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">@sliderDto.Header</h1>
                            <p class="mx-md-5 px-5 animate__animated animate__bounceIn">
                                @sliderDto.Content
                            </p>
                            <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="carousel-item position-relative" style="height: 430px;">
                    <img class="position-absolute w-100 h-100" src="@sliderDto.Image" style="object-fit: cover;">
                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                        <div class="p-3" style="max-width: 700px;">
                            <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">@sliderDto.Header</h1>
                            <p class="mx-md-5 px-5 animate__animated animate__bounceIn">
                                @sliderDto.Content
                            </p>
                            <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

MultiShop.Presentation/Views/Shared/Components/SliderRight/Default.cshtml
@using MultiShop.Business

@model List<SliderDto>

@foreach (SliderDto sliderDto in Model)
{

    <div class="product-offer mb-30" style="height: 200px;">
        <img class="img-fluid" src="@sliderDto.Image" alt="">
        <div class="offer-text">
            <h6 class="text-white text-uppercase">Save 20%</h6>
            <h3 class="text-white mb-3">@sliderDto.Header</h3>
            <a href="" class="btn btn-primary">Shop Now</a>
        </div>
    </div>


}

MultiShop.Presentation/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>MultiShop - Online Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="~/ui/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/ui/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/ui/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/ui/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    @await Component.InvokeAsync("TopBar")
    <!-- Topbar End -->
    <!-- Navbar Start -->
    @await Component.InvokeAsync("NavBar")
    <!-- Navbar End -->
    @RenderBody()
    <!-- Footer Start -->
    @await Component.InvokeAsync("Footer")
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>
    <img src="~/ui/~/ui/img/product-5.jpg" />

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/ui/lib/easing/easing.min.js"></script>
    <script src="~/ui/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="~/ui/mail/jqBootstrapValidation.min.js"></script>
    <script src="~/ui/mail/contact.js"></script>
    <!-- Template Javascript -->
    <script src="~/ui/js/main.js"></script>
</body>

</html>